# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'
  - script: sudo apt install nodejs
    displayName: 'npm install'
  - script: sudo npm install -g npm
    displayName: 'npm install selenium-webdriver '
  - script: sudo npm install -g npm
    displayName: 'npm test'
  - script: sudo node test/search_uopolo.js
    continueOnError: true
  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: junit-results.xml